### ISSUE TITLE
Missing callback handle_notification

### ISSUE THREAD

**Issue by csuriano23** [membraneframework/membrane_demo#199]
Hi there,
I was running the webrtc/videoroom demo, but I'm stuck with an error when entering a room; I can get in and see my video as room member, but after few seconds I'am redirected to the welcome form, seeing this stacktrace:

```text
07:24:03.897 [error] GenServer #PID<0.8605.0> terminating
** (FunctionClauseError) no function clause matching in Membrane.RTC.Engine.do_handle_notification/4
    (membrane_rtc_engine 0.1.0) lib/membrane_rtc_engine/engine.ex:1: Membrane.RTC.Engine.do_handle_notification({:new_track, "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7:f6a05dbd-1fbf-46c5-8e97-ced9c05352b1", nil, :OPUS, %Membrane.RTP.DepayloaderBin{clock_rate: 48000, depayloader: Membrane.RTP.Opus.Depayloader}}, {:endpoint, "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7"}, %Membrane.Pipeline.CallbackContext.Notification{children: %{{:endpoint, "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7"} => %Membrane.ChildEntry{clock: nil, component_type: :bin, module: Membrane.RTC.Engine.Endpoint.WebRTC, name: {:endpoint, "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7"}, options: %Membrane.RTC.Engine.Endpoint.WebRTC{extensions: %{}, filter_codecs: &Membrane.WebRTC.SDP.filter_mappings/1, handshake_opts: [client_mode: false, dtls_srtp: true, pkey: <<48, 130, 4, 164, 2, 1, 0, 2, 130, 1, 1, 0, 203, 129, 170, 232, 157, 219, 90, 247, 174, 183, 58, 1, 116, 131, 141, 82, 193, 251, 214, 229, 95, 41, 161, 28, 179, ...>>, cert: <<48, 130, 2, 210, 48, 130, 1, 186, 2, 1, 1, 48, 13, 6, 9, 42, 134, 72, 134, 247, 13, 1, 1, 5, 5, 0, 48, 47, 49, 11, 48, 9, 6, 3, 85, 4, ...>>], ice_name: "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7", integrated_turn_domain: nil, integrated_turn_options: [], log_metadata: [peer_id: "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7"], owner: #PID<0.8604.0>, port_range: 0..0, rtc_engine: #PID<0.8605.0>, rtcp_receiver_report_interval: nil, rtcp_sender_report_interval: nil, stun_servers: [%{server_addr: "stun.l.google.com", server_port: 19302}], trace_context: [], turn_servers: [], use_integrated_turn: false, video_tracks_limit: nil, webrtc_extensions: []}, pid: #PID<0.8607.0>, playback_sync: :synced, spec_ref: #Reference<0.1060270905.3169845250.10604>, sync: :membrane_no_sync, terminating?: false}}, clock: #PID<0.8606.0>, playback_state: :playing}, %{component_path: "pipeline@<0.8605.0>", display_manager: nil, endpoints: %{"670ee9f8-8c9a-40cf-8117-fc31c07d0ea7" => %Membrane.RTC.Engine.Endpoint{id: "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7", inbound_tracks: %{"670ee9f8-8c9a-40cf-8117-fc31c07d0ea7:f636a242-ed10-4544-aad7-adfe3d52ca31" => %Membrane.RTC.Engine.Track{active?: true, ctx: %{Membrane.WebRTC.Extension => [], :clock_rate => 90000}, encoding: :VP8, fmtp: nil, format: [:RTP, :raw], id: "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7:f636a242-ed10-4544-aad7-adfe3d52ca31", metadata: %{}, stream_id: "796713dc-6cbe-45bb-98c0-6c24b381bd42", type: :video}, "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7:f6a05dbd-1fbf-46c5-8e97-ced9c05352b1" => %Membrane.RTC.Engine.Track{active?: true, ctx: %{Membrane.WebRTC.Extension => [], :clock_rate => 48000}, encoding: :OPUS, fmtp: %ExSDP.Attribute.FMTP{apt: nil, cbr: nil, dtmf_tones: nil, level_asymmetry_allowed: nil, max_br: nil, max_dpb: nil, max_fr: nil, max_fs: nil, max_mbps: nil, max_smbps: nil, maxaveragebitrate: nil, maxplaybackrate: nil, minptime: 10, packetization_mode: nil, profile_id: nil, profile_level_id: nil, pt: 111, redundant_payloads: nil, repair_window: nil, rtx_time: nil, stereo: nil, usedtx: nil, useinbandfec: true}, format: [:RTP, :raw], id: "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7:f6a05dbd-1fbf-46c5-8e97-ced9c05352b1", metadata: %{}, stream_id: "796713dc-6cbe-45bb-98c0-6c24b381bd42", type: :audio}}}}, filters: %{}, id: "pippo", peers: %{"670ee9f8-8c9a-40cf-8117-fc31c07d0ea7" => %Membrane.RTC.Engine.Peer{id: "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7", metadata: %{"displayName" => "ada"}}}, subscriptions: %{"670ee9f8-8c9a-40cf-8117-fc31c07d0ea7" => %{}}, trace_context: [%{{:otel_tracer, :span_ctx} => {:span_ctx, 61545735463937995287510675882851046603, 5511311407862614268, 1, :undefined, true, :undefined, true, {:otel_span_ets, #Function<1.129312512/1 in :otel_tracer_server.on_end/1>}}}], waiting_for_linking: %{"670ee9f8-8c9a-40cf-8117-fc31c07d0ea7" => #MapSet<[]>}})
    (membrane_core 0.9.0) lib/membrane/core/callback_handler.ex:126: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 0.9.0) lib/membrane/core/callback_handler.ex:71: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
    (membrane_core 0.9.0) lib/membrane/core/parent/message_dispatcher.ex:35: Membrane.Core.Parent.MessageDispatcher.handle_message/2
    (stdlib 3.15.2) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.15.2) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {Membrane.Core.Message, :notification, [{:endpoint, "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7"}, {:new_track, "670ee9f8-8c9a-40cf-8117-fc31c07d0ea7:f6a05dbd-1fbf-46c5-8e97-ced9c05352b1", nil, :OPUS, %Membrane.RTP.DepayloaderBin{clock_rate: 48000, depayloader: Membrane.RTP.Opus.Depayloader}}], []}
```

Is there some callback implementation missing?

**Comment by csuriano23** [comment]
Sorry, I don't encounter the issue on the latest stable (v0.9.1), but only on master

**Comment by mickel8** [comment]
Hi @csuriano23,
thanks for the report. We have to update this demo to use the newest RTC Engine (0.4.0). You can also take a look at [`membrane_videoroom`](https://github.com/membraneframework/membrane_videoroom) demo which is a little more advanced example.

**Comment by csuriano23** [comment]
Great, thank you
